### PR TITLE
Added Select All toggle

### LINKED ISSUE #252: Add "Select All" to tracks table
Add a "select all" column to tracks table

### PR DESCRIPTION
**Pull request by etroo44**
Hello, I have successfully added the select all toggle to the tracks table.

Closes #252

### CODE REVIEW

**Comment by NeoCoderMatrix86** [comment]
Thanks for your contribution 👍 . I did some checks and would like you to change some minor stuff:
1. The "Select All" checkbox doesn't react to a track beeing unselected. As a user I would expect a state like "partly selected":
grafik

2. The code can be shortened:
`<Check TValue="bool" CheckedChanged="SelectAllTracks" Checked="selectedTracks.Any()" />`

```
void SelectAllTracks(bool select)
    {
        if(select)
        {
            selectedTracks.AddRange(Cuesheet.Tracks);
        }
        else
        {
            selectedTracks.Clear();
        }
    }
```
3. The method "SelectAllTracks" should be starting with "On", for example "OnSelectAllTracksChanged".

If you could edit these things, I will include the pull request. I would be happy to see more contributions from you, so if you want, have a look around the issues ;).

**Review by NeoCoderMatrix86 — CHANGES_REQUESTED** [review]
Thanks for your contribution 👍 . I did some checks and would like you to change some minor stuff:
1. The "Select All" checkbox doesn't react to a track beeing unselected. As a user I would expect a state like "partly selected":
grafik

2. The code can be shortened:
`<Check TValue="bool" CheckedChanged="SelectAllTracks" Checked="selectedTracks.Any()" />`

```
void SelectAllTracks(bool select)
    {
        if(select)
        {
            selectedTracks.AddRange(Cuesheet.Tracks);
        }
        else
        {
            selectedTracks.Clear();
        }
    }
```
3. The method "SelectAllTracks" should be starting with "On", for example "OnSelectAllTracksChanged".

If you could edit these things, I will include the pull request. I would be happy to see more contributions from you, so if you want, have a look around the issues ;).

**Comment by etroo44** [comment]
Sure no problem, I'll fix it and create a new pull request.

**Comment by etroo44** [comment]
Hey, I changed the Select All functionality as you wanted and fixed some bugs, you forgot to remove a track from the selectedTracks list when removing a track from Cuesheet.Tracks.

**Review by NeoCoderMatrix86 — CHANGES_REQUESTED** [review]
Thanks for your contribution and the fixes in code! I really appriciate this :).

What I am missing is the feature of the new select all, that not all tracks are selected. I wasn't clear I see, so I have a screenshot here from blazorise examples:

grafik

The example can be found here: https://bootstrap5demo.blazorise.com/tests/datagrid

This should be included and then the feature is done :).

**Comment by etroo44** [comment]
Okay, no problem. I hope everything is now as you wanted.

**Review by NeoCoderMatrix86 — APPROVED** [review]

**Comment by NeoCoderMatrix86** [comment]
Thanks for your contribution, now everything works fine. Also thanks for fixing bugs, I'll look forward for more contributions from you :).

**Pull request merged**
